spring:
    profiles:
        active:
        -dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-wow-dev
----
spring:
    profiles: test
    application:
        name: microservicecloud-config-wow-test